"""Initial schema

Revision ID: 2a8707851afe
Revises: 
Create Date: 2025-11-10 22:29:17.205828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8707851afe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(length=60), nullable=True),
    sa.Column('msisdn', sa.String(length=12), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pay_ref', sa.String(), nullable=True),
    sa.Column('pay_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'SENT', 'PAID', 'CANCELLED', 'FAILED')", name='ck_invoice_status'),
    sa.CheckConstraint('LENGTH(description) >= 3 AND LENGTH(description) <= 120', name='ck_invoice_description_length'),
    sa.CheckConstraint('LENGTH(msisdn) = 12', name='ck_invoice_msisdn_length'),
    sa.CheckConstraint('amount_cents >= 100', name='ck_invoice_amount_min'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("channel IN ('WHATSAPP', 'SMS')", name='ck_message_log_channel'),
    sa.CheckConstraint("direction IN ('IN', 'OUT')", name='ck_message_log_direction'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mpesa_receipt', sa.String(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('raw_request', sa.JSON(), nullable=True),
    sa.Column('raw_callback', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("method IN ('MPESA_STK')", name='ck_payment_method'),
    sa.CheckConstraint("status IN ('INITIATED', 'SUCCESS', 'FAILED', 'EXPIRED')", name='ck_payment_status'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('message_log')
    op.drop_table('invoices')
    # ### end Alembic commands ###
