"""Add vat_amount and merchant_msisdn to invoices

Revision ID: 3b9812b64c5f
Revises: 2a8707851afe
Create Date: 2025-11-22 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9812b64c5f'
down_revision: Union[str, None] = '2a8707851afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add merchant_msisdn column (nullable at first to allow existing data)
    op.add_column('invoices', sa.Column('merchant_msisdn', sa.String(length=12), nullable=True))

    # Add vat_amount column with default 0
    op.add_column('invoices', sa.Column('vat_amount', sa.Integer(), nullable=False, server_default='0'))

    # For existing rows, set merchant_msisdn to a default value (can be updated later)
    # In production, you would want to update this with actual merchant data
    op.execute("UPDATE invoices SET merchant_msisdn = '254700000000' WHERE merchant_msisdn IS NULL")

    # Now make merchant_msisdn non-nullable
    op.alter_column('invoices', 'merchant_msisdn', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'vat_amount')
    op.drop_column('invoices', 'merchant_msisdn')
    # ### end Alembic commands ###
